data:
  dataset_name : 'adidas'
  dataset_version : null
  input_size : 128
  target_size : 64
  evaluate_tag : 'test'

model:
  padding_side : 'left'
  # Updated to automatically determine the base model for prompt
  # base_model_for_prompt : 'gpt2-medium' # 'gpt2-medium' # 'gpt2-xl' # 'meta-llama/Llama-3.1-8B'


access_token: '...'

results_dir : './results/'
logs_dir : './evaluation/'
models_dir : './models/'
