data:
  dataset_name : 'e2e_nlg_cleaned'
  dataset_version : null
  input_size : 128
  target_size : 64
  evaluate_tag : 'test'

model:
  padding_side : 'left'
  base_model_for_prompt : 'gpt2-medium' # 'gpt2-medium' # 'gpt2-xl' # 'meta-llama/Llama-3.1-8B'

access_token: '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'

results_dir : './results/'
logs_dir : './logs/evaluation/'
models_dir : './models/'
