data:
  dataset_name : 'e2e_nlg_cleaned'
  dataset_version : null
  input_size : 128
  target_size : 64
  evaluate_tag : 'test'

model:
  padding_side : 'left'
  base_model_for_prompt : 'gpt2-medium' # 'gpt2-medium' # 'gpt2-xl' # 'meta-llama/Llama-3.1-8B'

access_token: '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'

results_dir : './results/'
logs_dir : './logs/evaluation/'
models_dir : './models/'
